paths: {}

components:
  parameters:
    pageNumber:
      name: page
      in: query
      description: 'page number'
      schema:
        type: integer
        default: 0
    pageSize:
      name: size
      in: query
      description: 'number per page'
      schema:
        type: integer
        default: 20