drop table processingerror;
drop table processingerrors;
drop table diagnostic;
drop table diagnostics;
drop table documentevents;
drop table document;
drop table documents;
drop table executions;
drop table flyway_schema_history;
