apiVersion: v1
kind: Service
metadata:
  name: {{ include "search.fullname" . }}-actuator
  labels:
    app.kubernetes.io/component: metrics
    {{- include "search.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: actr-port
      port: 8031
      targetPort: 8031
      protocol: TCP
  selector:
    {{- include "search.selectorLabels" . | nindent 4 }}
