apiVersion: v1
kind: Service
metadata:
  name: {{ include "search.fullname" . }}-service
  labels:
    {{- include "search.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: srvc-port
      port: 8030
      targetPort: 8030
      protocol: TCP
  selector:
    {{- include "search.selectorLabels" . | nindent 4 }}
