#
# Default values for acceptation environment.
# https://helm.sh/docs/topics/chart_best_practices/values/#document-values-yaml
#

# Function and image name in deployment manifest
app: template

# Amount of Pods to be spinned-up
replicaCount: 1

# Registry from which images will be pulled on deployment
registry:SSSSSSSSSSSSSSSSSSSS

# Path in the registry from which the image will be pulled
project: koop-plooi

# Environment variables
location_url: "https://open-sdb.overheid.nl/overheid/openbaarmaken/api/v0/documenten/"
pid_endpoint: "https://open-sdb.overheid.nl/documenten/"
dcn_host:SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS

# Image version
appVersion: "latest"

# Using Never for local testing purposes
imagePullPolicy: Always

# Registry credentials; is ignored when imagePullPolicy=Never
imagePuller: harbor-puller

# Rules for incoming network traffic
ingress:
  # DNS
  url: open-sdb.overheid.nl
  tls:
    # Defines server-certificate
    secret: open-sdb-secret