apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "mockserver.fullname" . }}-ingress
  labels:
    {{- include "mockserver.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  rules:
    - host: {{ include "mockserver.fullname" . }}.{{ .Values.ingress.hostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "mockserver.fullname" . }}-service
                port:
                  number: 1080
