apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "portal.fullname" . }}
  labels:
    app: {{ include "portal.fullname" . }}
    {{- include "portal.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "portal.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      name: plooi-portal
      labels:
        {{- include "portal.selectorLabels" . | nindent 8 }}
        {{- if .Values.podLabels }}
          {{- include "common.tplvalues.render" (dict "value" .Values.podLabels "context" $) | nindent 8 }}
        {{- end }}
        timestamp: "{{ now | unixEpoch }}"
    spec:
      imagePullSecrets:
        - name: harbor-puller
      containers:
        - name: {{ .Chart.Name }}
          image:  {{ .Values.image.registry }}{{ .Values.image.image }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
              name: plooi-portal
          livenessProbe:
            httpGet:
              path: /cb-common/2.0.0/images/logo.svg
              port: 8080
            initialDelaySeconds: {{ .Values.deployment.livelinessDelay }}
            timeoutSeconds: 25
          readinessProbe:
            httpGet:
              path: /cb-common/2.0.0/images/logo.svg
              port: 8080
            initialDelaySeconds: {{ .Values.deployment.readinessDelay }}
            timeoutSeconds: 25
          {{- if .Values.resources }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
