-- Updated time related columns : add timezone data
ALTER TABLE DOCUMENTEVENTS ALTER COLUMN time_created TYPE TIMESTAMP WITH TIME ZONE;
ALTER TABLE EXECUTIONS ALTER COLUMN time_created TYPE TIMESTAMP WITH TIME ZONE;
ALTER TABLE PROCESSINGERRORS ALTER COLUMN time_created TYPE TIMESTAMP WITH TIME ZONE;
ALTER TABLE PROCESSINGERRORS ALTER COLUMN time_updated TYPE TIMESTAMP WITH TIME ZONE;