# Default values for the registration component service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2
nameOverride: ""
fullnameOverride: ""

logLevel: INFO
extraJvmArgs: ""

database:
  url: ""
  secret: ""

process:
  url:SSSSSSSSSSSSSSSSSSSSSSSSSSSS

image:
  registry: ""
  pullPolicy: Always
  tag: latest

podLabels: {}

ingress:
  ingressClassName: nginx
  hostname: registratie.127.0.0.1.nip.io

metrics:
  enabled: false
  serviceMonitor:
    enabled: false
    namespace: ""
    interval: ""
    scrapeTimeout: ""

opentelemetry:
  enabled: false
  traces:
    exporter: none
  metrics:
    exporter: none
