openapi: 3.0.3

info:
  title: ClamAV API
  description: OpenAPI specificatie voor de ClamAV service.
  version: 1.0.0

paths:
  /ping:
    get:
      operationId: pingDeamon
      description: Ping de Clam AV deamon.
      responses:
        200:
          description: De deamon is online.
          content:
            application/json:
              schema:
                type: string
        400:
          description: De deamon is offline

  /clam/scan:
    post:
      operationId: ScanDocument
      description: Scant een document op eventuele fouten.
      requestBody:
        required: true
        description: Het document dat gescand moet worden door ClamAV.
        content:
          application/octet-stream:
            schema:
              type: string
              format: byte
      responses:
        200:
          description: Het scannen van het document is geslaagd.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/scanPassed'
        400:
          description: Fout in het bestand.

components:
  schemas:
    scanPassed:
      type: object
      properties:
        title:
          type: string
