kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: plooi-backup-pvc
  labels:
    plooi-backup: dcn-backup
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  storageClassName: nfs
