apiVersion: v1
kind: Service
metadata:
  name: {{ include "dictionary.fullname" . }}-service
  labels:
    {{- include "dictionary.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: srvc-port
      port: 8030
      targetPort: 8030
      protocol: TCP
  selector:
    {{- include "dictionary.selectorLabels" . | nindent 4 }}
