apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "dcn.fullname" . }}-actuator-ingress
  labels:
    {{- include "dcn.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/app-root: /actuator/hawtio
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  rules:
    - host: {{ include "dcn.fullname" . }}-actuator.{{ .Values.ingress.hostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "dcn.fullname" . }}-actuator-service
                port:
                  number: 8081
