apiVersion: v1
kind: Service
metadata:
  name: {{ include "dcn.fullname" . }}-actuator-service
  labels:
    app.kubernetes.io/component: metrics
    {{- include "dcn.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: dcn-actr-port
      port: 8081
      targetPort: 8081
      protocol: TCP
  selector:
    {{- include "dcn.selectorLabels" . | nindent 4 }}
