apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "repository.fullname" . }}-service-ingress
  labels:
    {{- include "repository.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  rules:
    - host: {{ include "repository.fullname" . }}-service.{{ .Values.ingress.hostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "repository.fullname" . }}-service
                port:
                  number: 8010
