apiVersion: v1
kind: Service
metadata:
  name: {{ include "repository.fullname" . }}-actuator
  labels:
    app.kubernetes.io/component: metrics
    {{- include "repository.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: actr-port
      port: 8011
      targetPort: 8011
      protocol: TCP
  selector:
    {{- include "repository.selectorLabels" . | nindent 4 }}
