apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "registration.fullname" . }}-service-ingress
  labels:
    {{- include "registration.labels" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  rules:
    - host: {{ include "registration.fullname" . }}-service.{{ .Values.ingress.hostname }}
      http:
        paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: {{ include "registration.fullname" . }}-service
                  port:
                    number: 8020