apiVersion: v1
kind: Service
metadata:
  name: {{ include "registration.fullname" . }}-actuator
  labels:
    app.kubernetes.io/component: metrics
    {{- include "registration.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: actr-port
      port: 8021
      targetPort: 8021
      protocol: TCP
  selector:
    {{- include "registration.selectorLabels" . | nindent 4 }}
